---

- name: Admin playbook
  hosts: all
  gather_facts: true

  vars_files:
    - vars/global-vars.yaml
    - vars/osx-global-defaults.yaml
    - vars/osx-local-defaults.yaml
    - vars/admin-global-vars.yaml
    - vars/{{ 'admin-' ~ computer.model | lower ~ '-vars' }}.yaml

  vars_prompt:
    - name: user.password
      prompt: Enter password for User {{ user.name }}
      confirm: true
      private: true

  handlers:
    - name: Include Handlers
      ansible.builtin.import_tasks: handlers/main.yaml

  pre_tasks:
    - name: Create variables to be used in the following Roles & Tasks
      ansible.builtin.include_tasks: tasks/admin-pre-task.yaml

  roles:
    - role: geerlingguy.mac.homebrew
      tags: homebrew
    - role: geerlingguy.mac.mas
      tags: mas
    - role: geerlingguy.mac.dock
      tags: dock

  tasks:
    - name: Include other-casks
      ansible.builtin.include_tasks: tasks/install-other-casks.yaml
      tags: casks
    - name: Include set-defaults
      ansible.builtin.include_tasks: tasks/set-defaults.yaml
      tags: defaults
    - name: Include admin-config
      ansible.builtin.include_tasks: tasks/admin-config.yaml
      tags: config
    - name: Include config-hardware
      ansible.builtin.include_tasks: tasks/config-hardware.yaml
      tags: hardware
    - name: Include set-hostname
      ansible.builtin.include_tasks: tasks/set-hostname.yaml
      tags: hostname
    - name: Include create-user
      ansible.builtin.include_tasks: tasks/create-user.yaml
      tags: user
    - name: Change ownership of macos-setup directories
      ansible.builtin.include_tasks: tasks/change-ownership.yaml
      tags: owner
