---
- hosts: all

  vars_files:
    - vars/admin_setup.yml
    - vars/osx-defaults.yml

  pre_tasks:
    - name: Modify MAS task
      delegate_to: localhost
      ansible.builtin.replace:
        path: "{{ lookup('env', 'PWD') }}/roles/geerlingguy.mas/tasks/main.yml"
        regexp: \s([']?)(mas)\s
        replace: ' \1/usr/local/bin/\2 '
      tags: always

  roles:
    - role: geerlingguy.homebrew
      when: homebrew_cask_apps
      tags: homebrew
    - role: geerlingguy.mas
      when: mas_installed_apps
      tags: mas

  tasks:
    - ansible.builtin.include_tasks: tasks/install-other-casks.yml
      tags: homebrew
    - ansible.builtin.include_tasks: tasks/modify-dock.yml
      tags: dock
    - ansible.builtin.include_tasks: tasks/set-defaults.yml
      tags: osx
    - ansible.builtin.include_tasks: tasks/admin-config.yml

  handlers:
    - ansible.builtin.import_tasks: handlers/main.yml