---
- hosts: all

  vars:
    user_name: "Jon Hogg"
    user_abbr: "jonhogg"

  vars_prompt:
    - name: user_pw
      prompt: Enter password for user {{ user_name }}
      confirm: yes
      private: yes
      # encrypt: sha512_crypt
      # salt_size: 7

  vars_files:
    - vars/osx-global-defaults.yaml
    - vars/osx-local-defaults.yaml
    - vars/{{ 'admin_setup_mbp' if ansible_model is search("MacBookPro") else 'admin_setup_imac' }}.yaml

  handlers:
    - ansible.builtin.import_tasks: handlers/main.yaml

  roles:
    - role: geerlingguy.mac.homebrew
      when: homebrew_cask_apps is defined or homebrew_installed_packages is defined
      tags: homebrew
    - role: geerlingguy.mac.mas
      when: mas_installed_apps is defined
      tags: mas
    - role: geerlingguy.mac.dock
      when: dockitems_remove is defined or dockitems_persist is defined
      tags: dock

  tasks:
    - ansible.builtin.include_tasks: tasks/install-other-casks.yaml
      tags: homebrew
    - ansible.builtin.include_tasks: tasks/set-defaults.yaml
      tags: defaults
    - ansible.builtin.include_tasks: tasks/admin-config.yaml
      tags: config
    - ansible.builtin.include_tasks: tasks/hardware.yaml
      tags: hardware
    - ansible.builtin.include_tasks: tasks/set-hostname.yaml
      tags: hostname
    - ansible.builtin.include_tasks: tasks/setup-user.yaml
      tags: user
    - ansible.builtin.include_tasks: tasks/change-ownership.yaml
      tags: owner
