---

- name: User playbook
  hosts: all
  gather_facts: true

  vars_files:
    - vars/global-vars.yaml
    - vars/osx-local-defaults.yaml
    - vars/user-global-vars.yaml

  handlers:
    - name: Include Handlers
      ansible.builtin.import_tasks: handlers/main.yaml

  roles:
    - role: geerlingguy.mac.homebrew
      tags: homebrew
    - role: geerlingguy.mac.mas
      tags: mas
    - role: geerlingguy.mac.dock
      tags: dock

  pre_tasks:
    - name: Create variables to be used in the following Roles & Tasks
      ansible.builtin.include_tasks: tasks/user-pre-task.yaml
      tags: vars
    - name: Change ownership of Homebrew directories
      ansible.builtin.include_tasks: tasks/change-ownership.yaml
      tags: owner

  tasks:
    - name: Include set-defaults
      ansible.builtin.include_tasks: tasks/set-defaults.yaml
      tags: defaults
    - name: Include user-config
      ansible.builtin.include_tasks: tasks/user-config.yaml
      tags: config
    - name: Include setup-developer
      ansible.builtin.include_tasks: tasks/setup-developer-dirs.yaml
      tags: develop
    - name: Include create-dir-links
      ansible.builtin.include_tasks: tasks/create-dir-links.yaml
      tags: dirlinks
    - name: Include link-dotfiles
      ansible.builtin.include_tasks: tasks/link-dotfiles.yaml
      tags: dotfiles
    - name: Include setup-apps
      ansible.builtin.include_tasks: tasks/setup-apps.yaml
      tags: apps
    - name: Include setup-login-items
      ansible.builtin.include_tasks: tasks/setup-login-items.yaml
      tags: login
    - name: Include setup-launch-agent
      ansible.builtin.include_tasks: tasks/setup-launch-agent.yaml
      tags: launch
    - name: Include modify-finder
      ansible.builtin.include_tasks: tasks/modify-finder.yaml
      tags: finder
    - name: Include iMac tasks
      when: computer_model == "iMac"
      block:
        - name: Include modify-keyboard
          ansible.builtin.include_tasks: tasks/modify-keyboard.yaml
          tags: keyboard
        - name: Include setup-printer
          ansible.builtin.include_tasks: tasks/setup-printer.yaml
          tags: printer
        - name: Include setup-games
          ansible.builtin.include_tasks: tasks/setup-games.yaml
          tags: games
