---
- hosts: all

  vars_files:
    - user_setup.yml
    - osx-defaults.yml

  roles:
    - role: userconfig

  tasks:
    - ansible.builtin.include_tasks: modify-dock.yml
      tags: dock
    - ansible.builtin.include_tasks: set-defaults.yml
      tags: osx
