---
- hosts: all

  vars_files:
    - vars/user_setup.yml
    - vars/osx-defaults.yml

  tasks:
    - ansible.builtin.include_tasks: tasks/modify-dock.yml
      tags: dock
    - ansible.builtin.include_tasks: tasks/set-defaults.yml
      tags: osx
    - ansible.builtin.include_tasks: tasks/user-config.yml

 handlers:
    - ansible.builtin.import_tasks: handlers/main.yml