---

- name: Setup variables to be used in the following roles and tasks
  ansible.builtin.set_fact:
    homebrew_taps: "{{ homebrew_taps_admin | union( vars['homebrew_taps_' ~ computer.model] ) }}"
    homebrew_installed_packages: "{{ homebrew_installed_packages_admin | union( vars['homebrew_installed_packages_' ~ computer.model] ) }}"
    homebrew_cask_apps: "{{ homebrew_cask_apps_admin | union( vars['homebrew_cask_apps_' ~ computer.model] ) }}"
    homebrew_cask_apps_sudo: "{{ homebrew_cask_apps_sudo_admin | union( vars['homebrew_cask_apps_sudo_' ~ computer.model] ) }}"
    homebrew_cask_apps_local: "{{ homebrew_cask_apps_local_admin | union( vars['homebrew_cask_apps_local_' ~ computer.model] ) }}"
    mas_installed_apps: "{{ mas_installed_apps_admin | union( vars['mas_installed_apps_' ~ computer.model] ) }}"
    pip_items: "{{ pip_items_admin | union( vars['pip_items_' ~ computer.model] ) }}"
    gem_items: "{{ gem_items_admin | union( vars['gem_items_' ~ computer.model] ) }}"
    npm__items: "{{ npm__items_admin | union( vars['npm_items_' ~ computer.model] ) }}"
    dockitems_remove: "{{ dockitems_remove_gvars | union(dockitems_remove_admin) | union( vars['dockitems_remove_' ~ computer.model] ) }}"
    dockitems_persist: "{{ dockitems_persist_gvars | union(dockitems_persist_admin) | union( vars['dockitems_persist_' ~ computer.model] ) }}"
