---
# tasks for change-ownership

- name: Change ownership to {{ user_abbr }}
  block:
    - name: Recursively change ownership of macos-setup repo
      become: true
      ansible.builtin.file:
        path: /Users/Shared/macos-setup
        state: directory
        recurse: true
        owner: "{{ user_abbr }}"
        group: staff
    - name: Recursively change ownership of Homebrew directories
      become: true
      ansible.builtin.file:
        path: "{{ hb_dir }}"
        state: directory
        recurse: true
        owner: "{{ user_abbr }}"
        group: staff
