---
# tasks for change-ownership

- name: Change ownership to {{ user_abbr }}
  block:
    - name: Recursively change ownership of macos-setup repo
      when: "homebrew_cask_apps_admin is defined"
      become: true
      ansible.builtin.file:
        path: /Users/Shared/macos-setup
        state: directory
        recurse: true
        owner: "{{ user_abbr }}"
        group: "{{ user_group }}"
    - name: Recursively change ownership of Homebrew directories
      when: "homebrew_cask_apps_user is defined"
      become: true
      ansible.builtin.file:
        path: "{{ homebrew_prefix }}/*"
        state: directory
        recurse: true
        owner: "{{ user_abbr }}"
        group: "{{ user_group }}"
