---
- block:
  - name: Recursively change ownership of macos-setup repo
    become: yes
    ansible.builtin.file:
      path: /Users/Shared/macos-setup
      state: directory
      recurse: yes
      owner: "{{ user_abbr }}"
      group: staff
  - name: Recursively change ownership of Homebrew directories
    become: yes
    ansible.builtin.file:
      path: "{{ hb_dir }}"
      state: directory
      recurse: yes
      owner: "{{ user_abbr }}"
      group: staff
