---
# tasks for create-dir-links

- name: Hide directories & remove Cloud Storage entries
  block:
    - name: Hide directories
      ansible.builtin.command: "chflags hidden ~/{{ item | ansible.builtin.quote }}"
      loop:
        - Documents
        - Movies
        - Music
        - Pictures
    - name: Remove links to CloudStorage entries
      ansible.builtin.file:
        path: "$HOME/{{ item }}"
        state: absent
      loop:
        - "Dropbox"
        - "Google Drive"
        - "OneDrive"

- name: Create external drive links
  when: computer.model is "iMac"
  block:
    - name: Create media directory links
      ansible.builtin.file:
        src: "/Volumes/Media/{{ item }}"
        path: "$HOME/My-{{ item }}"
        state: link
        force: true
        follow: false
      loop:
        - Movies
        - Music
        - Pictures
    - name: Create games directory link
      ansible.builtin.file:
        src: "/Volumes/Games"
        path: "$HOME/Games"
        state: link
        force: true
        follow: false
