---

- name: Install cask applications that require sudo
  when: homebrew_cask_apps_sudo is defined
  community.general.homebrew_cask:
    name: "{{ item.name | default(item) }}"
    state: present
    install_options: "{{ item.install_options | default('appdir=' ~ homebrew_cask_appdir) }}"
    accept_external_apps: "{{ homebrew_cask_accept_external_apps }}"
    sudo_password: mac_admin_pw
  loop:
    - "{{ homebrew_cask_apps_sudo }}"
  notify:
    - Clear homebrew cache

- name: Install local casks apps
  when: homebrew_cask_apps_local is defined
  block:
    - name: Copy Cask files
      ansible.builtin.copy:
        src: "{{ item.name | default(item) }}.rb"
        dest: "{{ homebrew_prefix }}/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/"
        mode: '0644'
      loop:
        - "{{ homebrew_cask_apps_local }}"
    - name: Install local cask applications
      community.general.homebrew_cask:
        name: "{{ item.name | default(item) }}"
        state: present
        install_options: "{{ item.install_options | default('appdir=' ~ homebrew_cask_appdir) }}"
        accept_external_apps: "{{ homebrew_cask_accept_external_apps }}"
      loop:
        - "{{ homebrew_cask_apps_local }}"
      notify:
        - Clear homebrew cache
