---

- name: "Set Hostname to {{ computer.hostname }}"
  become: true
  ansible.builtin.command: "scutil --set {{ item }} {{ computer.hostname }}"
  loop:
    ComputerName
    LocalHostName
    HostName
  when: computer.hostname is defined
  tags: always
