---
- block:
  - name: "Set Hostname to {{ computer_hostname }}"
    become: yes
    ansible.builtin.command: "scutil --set {{ item }} {{ computer_hostname }}"
    with_items:
      - ComputerName
      - LocalHostName
      - HostName
    when: computer_hostname is defined
    tags: always