--- tasks for setting up Applications

- block:
  - name: Make links for Preference files
    ansible.builtin.file:
      src: "{{ db_prefix }}/OSX/Preferences/{{ item }}"
      path: "$HOME/Library/Preferences"
      state: link
      force: yes
      follow: no
     loop:
      - com.bombich.ccc.plist
      - com.bombich.cccdashboard.plist
      - com.clipy-app.Clipy.plist
      - com.googlecode.iterm2.plist
      - com.macromates.TextMate.plist
      - com.manytricks.Moom.plist
      - com.manytricks.NameMangler.plist
      - com.mothersruin.SuspiciousPackage.plist
      - com.mothersruin.SuspiciousPackageApp.plist
      - com.tiddlywiki.plist
      - com.torusknot.SourceTreeNotMAS.plist
      - eu.exelban.Stats.plist
      - org.hammerspoon.Hammerspoon.plist
      - org.pqrs.Karabiner-Elements.Preferences.plist
      - org.pqrs.Karabiner-Menu.plist
      - org.torproject.torbrowser.plist
      - org.videolan.vlc.plist
  - name: Make links for Preference files
    ansible.builtin.file:
      src: "{{ db_prefix }}/OSX/Preferences/{{ item }}"
      path: "$HOME/Library/Preferences"
      state: link
      force: yes
      follow: no
     loop:
      - com.bruji.cdpedia.plist
      - com.bruji.dvdpedia.plist
    when: ansible_model is search("iMac")
  - name: Create links for Library Application Support directories
    ansible.builtin.file:
      src: "{{ db_prefix }}/OSX/Library Links/Application Support/{{ item }}"
      path: "$HOME/Library/Application Support/{{ item }}"
      state: link
      force: yes
      follow: no
    loop:
      - CDPedia
      - DVDpedia
    when: ansible_model is search("iMac")
  - name: Create link for iTerm AutoLaunch script directory
    ansible.builtin.file:
      src: "{{ db_prefix }}/OSX/Library Links/Application Support/iTerm2/Scripts"
      path: "$HOME/Library/Application Support/iTerm2"
      state: link
      force: yes
      follow: no
  - name: Create link for TextMate bundle directory
    ansible.builtin.file:
      src: "{{ db_prefix }}/OSX/Library Links/Application Support/TextMate/{{ item }}"
      path: "$HOME/Library/Application Support/TextMate"
      state: link
      force: yes
      follow: no
    loop:
      - "Pristine Copy"
