---
# tasks for setting up Applications

- name: Create links for App preferences, iTerm & TextMate
  block:
    - name: Make links for Preference files
      ansible.builtin.file:
        src: "{{ dropbox_dir }}/OSX/Preferences/{{ item }}"
        path: "$HOME/Library/Preferences/{{ item }}"
        state: link
        force: true
        mode: '0644'
      loop:
        - com.bombich.ccc.plist
        - com.bombich.cccdashboard.plist
        - com.clipy-app.Clipy.plist
        # - com.googlecode.iterm2.plist
        - com.macromates.TextMate.plist
        - com.manytricks.Moom.plist
        - com.manytricks.NameMangler.plist
        - com.mothersruin.SuspiciousPackage.plist
        - com.mothersruin.SuspiciousPackageApp.plist
        - com.tiddlywiki.plist
        - com.torusknot.SourceTreeNotMAS.plist
        - eu.exelban.Stats.plist
        - org.hammerspoon.Hammerspoon.plist
        - org.pqrs.Karabiner-Elements.Preferences.plist
        - org.pqrs.Karabiner-Menu.plist
        - org.torproject.torbrowser.plist
        - org.videolan.vlc.plist
    - name: Create iTerm2 Scripts directory link
      block:
        - name: Create  parent directory if it doesn't exist
          ansible.builtin.file:
            path: "$HOME/Library/Application Support/iTerm2"
            state: directory
            mode: '0755'
        - name: Create link to iTerm Scripts directory
          ansible.builtin.file:
            src: "{{ dropbox_dir }}/OSX/Library Links/Application Support/iTerm2/Scripts"
            path: "$HOME/Library/Application Support/iTerm2/Scripts"
            state: link
            force: true
            mode: '0755'
    - name: Create TextMate Pristine Copy directory link
      block:
        - name: Create  parent directory if it doesn't exist
          ansible.builtin.file:
            path: "$HOME/Library/Application Support/TextMate"
            state: directory
            mode: '0755'
        - name: Create link for TextMate bundle directory
          ansible.builtin.file:
            src: "{{ dropbox_dir }}/OSX/Library Links/Application Support/TextMate/Pristine Copy"
            dest: "$HOME/Library/Application Support/TextMate/Pristine Copy"
            state: link
            mode: '0755'

- name: Create links for Apps & Preferences (iMac only)
  when: computer_model == "iMac"
  block:
    - name: Make links for Preference files (iMac)
      ansible.builtin.file:
        src: "{{ dropbox_dir }}/OSX/Preferences/{{ item }}"
        path: "$HOME/Library/Preferences/{{ item }}"
        state: link
      loop:
        - com.bruji.cdpedia.plist
        - com.bruji.dvdpedia.plist
    - name: Create links for Library Application Support directories (iMac)
      ansible.builtin.file:
        src: "{{ dropbox_dir }}/OSX/Library Links/Application Support/{{ item }}"
        path: "$HOME/Library/Application Support/{{ item }}"
        state: link
      loop:
        - CDPedia
        - DVDpedia
