---

- name: Setup Printer
  block:
    - name: Remove Printer
      ansible.builtin.command: lpadmin -x "Canon_iP4200___hc4server"
    - name: Add Printer, Enable and accept jobs on the printer
      ansible.builtin.shell: >-
        set -o pipefail
        lpadmin -m everywhere -p "Canon_iP4200___hc4server" -D "Canon iP4200 @ hc4server" -L "Breakfast Room" -v $(ippfind | head -1) -o printer-is-shared=false -E
