---
# tasks for setup-user

- name: Create user & add to sudoers
  block:
    - name: Create User
      become: true
      ansible.builtin.user:
        name: "{{ user_abbr }}"
        comment: "{{ user_name }}"
        password: "{{ user_pw }}"
        shell: '/bin/zsh'
        group: 'staff'
        append: true
        state: present
      register: result
    - name: Add User to sudoers
      become: true
      ansible.builtin.lineinfile:
        path: "/etc/sudoers.d/90_{{ user_abbr }}"
        line: "{{ user_abbr }} ALL = (ALL) ALL"
        create: true
        mode: 0440
        state: present
        validate: /usr/sbin/visudo -cf %s
