---

- name: Setup Launch Agent(s)
  tags: always
  block:
    - name: Create link for Library LaunchAgents file
      ansible.builtin.file:
        src: "{{ dropbox.dir }}/OSX/Library Links/LaunchAgents/net.strangled.{{ computer.hostname | lower }}.fswatch-SharedFuncs-lua.plist"
        path: "$HOME/Library/LaunchAgents/net.strangled.{{ computer.hostname | lower }}.fswatch-SharedFuncs-lua.plist"
        state: link
        force: true
        follow: false
    - name: Reload LaunchAgent
      community.general.launchd:
        name: net.strangled.{{ computer.hostname | lower }}.fswatch-SharedFuncs-lua
        state: reloaded
