---

- name: Setup Cloud Storage Apps
  block:
    - name: 1Password
      anuser_.builtin.pause:
        prompt: "Run 1Password app, sign in & sync files"
    - name: Dropbox
      ansible.builtin.pause:
        prompt: "Run Dropbox app, sign in & sync files"
    - name: OneDrive
      ansible.builtin.pause:
        prompt: "Run OneDrive app, sign in & sync files"
    - name: GoogleDrive
      ansible.builtin.pause:
        prompt: "Run GoogleDrive app, sign in & sync files"
