---

- name: Install other casks
  ansible.builtin.include_tasks: install-other-casks.yml

- name: Install Pip Libraries
  ansible.builtin.pip:
    name: "{{ item }}"
    extra_args: "--ignore-installed"
  with_items: "{{ pip_items }}"

- name: Install Ruby Gems
  community.general.gem:
    name: "{{ item }}"
  with_items: "{{ gem_items }}"

- name: Install Node Packages
  community.general.npm:
    name: "{{ item }}"
    global: yes
  with_items: "{{ npm_items }}"

- name: Modify the Dock
  include_tasks: modify-dock.yml

- name: Set Timezone
  become: yes
  community.general.timezone:
    name: "Europe/London"

- name: Set ZSH as the default shell
  become: yes
  shell: chsh -s $(which zsh) {{ lookup('env', 'USER') }}

- name: Setup User
  ansible.builtin.include_tasks: setup-user.yml
