---

- name: Create User
  become: yes
  ansible.builtin.user:
    name: jonhogg
    comment: Jon Hogg
    password: "mac_user_pw"
    group: staff
    update_password: on_create
  register: result

- name: Show User commmand output
  ansible.builtin.debug:
    var: result
  tags: debug

- name: Add User to sudoers
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/90_jonhogg
    line: jonhogg ALL = (ALL) ALL
    create: yes
    mode: 0440
    validate: /usr/sbin/visudo -cf %s
