---
# handlers for macos-setup

- name: Restart ControlCenter
  become: true
  ansible.builtin.command: killall ControlCenter
  listen: "restart controlcenter"

- name: Restart Dock
  become: true
  ansible.builtin.command: killall Dock
  listen: "restart dock"

- name: Restart Finder
  become: true
  ansible.builtin.command: killall Finder
  listen: "restart finder"

- name: Restart SystemUIServer
  become: true
  ansible.builtin.command: killall SystemUIServer
  listen: "restart systemuiserver"
