---

- name: Restart the Dock
  become: yes
  ansible.builtin.shell: killall Dock
  when: restart_dock

- name: Restart ControlCenter
  ansible.builtin.shell: killall ControlCenter
  when: restart_controlcenter

- name: Restart Finder
  ansible.builtin.shell: killall Finder
  when: restart_finder

- name: Restart SystemUIServer
  ansible.builtin.shell: killall SystemUIServer
  when: restart_systemuiserver
