---
  
- name: Configure UI
  block:
  # become: yes
    - name: Modify the Dock
      ansible.builtin.include_tasks: modify-dock.yml
      tags: dock

- name: Setup user defaults
  include_tasks: set-defaults.yml


# - name: Configure Apps
#   block:
#   become: yes
#     - name: Copy TextMate Bundles
#
#     - name: Setup Dropbox & 1Password
#
#     - name: Setup iTerm2
#
#     - name: Setup MenuMeters
#
#
#     - name: Set Wallpaper options
#
