---
  
- name: Install cask applications that require sudo
  community.general.homebrew_cask:
    name: "{{ item.name | default(item) }}"
    state: present
    install_options: "{{ item.install_options | default('appdir=' + homebrew_cask_appdir) }}"
    accept_external_apps: "{{ homebrew_cask_accept_external_apps }}"
    sudo_password: mac_user_pw
  loop: "{{ homebrew_cask_apps_sudo }}"
  notify:
    - Clear homebrew cache

- name: Quit Zoom
  ansible.builtin.shell: osascript -e 'quit app "zoom.us"'
  ignore_errors: yes

- name: Configure UI
  block:
  # become: yes
    - name: Modify the Dock
      ansible.builtin.include_tasks: modify-dock.yml
      tags: dock

- name: Setup user defaults
  include_tasks: set-defaults.yml


# - name: Configure Apps
#   block:
#   become: yes
#     - name: Copy TextMate Bundles
#
#     - name: Setup Dropbox & 1Password
#
#     - name: Setup iTerm2
#
#     - name: Setup MenuMeters
#
#
#     - name: Set Wallpaper options
#
